#! /bin/sh

wr() { if [ -e $1 ]; then echo $2 > $1; fi }

#############################################################
cd /proc/sys/net/core
#############################################################

wr netdev_max_backlog 1024
wr optmem_max 65536
wr rmem_default 131072
wr rmem_max 16777216
wr somaxconn 1024
wr wmem_default 131072
wr wmem_max 16777216

#############################################################
cd /proc/sys/net/ipv4/route
#############################################################

wr flush 1

#############################################################
cd /proc/sys/net/ipv4
#############################################################

wr ip_local_port_range "1024 65535"
wr tcp_app_win 0
wr tcp_fack 1
wr tcp_fin_timeout 30
wr tcp_keepalive_intvl 30
wr tcp_keepalive_probes 5
wr tcp_keepalive_time 600
wr tcp_max_orphans 8192
wr tcp_max_syn_backlog 8192
wr tcp_max_tw_buckets 8192
wr tcp_mtu_probing 1
wr tcp_no_metrics_save 1
wr tcp_low_latency 1
wr tcp_rmem "131072 131072 16777216"
wr tcp_rfc1337 1
wr tcp_slow_start_after_idle 0
wr tcp_synack_retries 3
wr tcp_syn_retries 3
wr tcp_tw_reuse 1
wr tcp_wmem "131072 131072 16777216"
wr udp_rmem_min 65536
wr udp_wmem_min 65536

#############################################################
cd /proc/sys/net/ipv6/conf/all
#############################################################

wr disable_ipv6 1

#############################################################
cd /proc/sys/net/unix
#############################################################

wr max_dgram_qlen 1024

#############################################################
exit 0
#############################################################
