#! /bin/sh

# Determine physical memory size in KB
RAM_KB="$(free | awk '/Mem/ {print $2}')"

# Define a function that only modifies settings if they exist
# Useful if using script across different kernel versions
wr() { if [ -e $1 ]; then echo $2 > $1; fi }

#############################################################
cd /proc/sys/debug
#############################################################

wr exception-trace 0

#############################################################
cd /proc/sys/kernel
#############################################################

wr msgmax 32768
wr msgmnb 65536
wr msgmni 8192
wr sched_latency_ns 1000000
wr sched_min_granularity_ns 500000
wr sched_migration_cost_ns 5000000
wr sched_rr_timeslice_ms 20
wr sched_rt_period_us 1000000
wr sched_rt_runtime_us 990000
wr sched_wakeup_granularity_ns 250000
wr shmall $(( $(( $RAM_KB * 500 )) / $(getconf PAGE_SIZE) )) 
wr shmmax $(( $RAM_KB * 500 ))
wr shmmni 4096
wr watchdog 0
wr watchdog_thresh 0

#############################################################
cd /proc/sys/net
#############################################################

wr core/dev_weight 1024
wr core/netdev_budget 1024
wr core/netdev_max_backlog 1024
wr core/optmem_max 65536
wr core/rmem_default 131072
wr core/rmem_max 16777216
wr core/somaxconn 1024
wr core/wmem_default 131072
wr core/wmem_max 16777216

wr ipv4/ip_local_port_range "1024 65535"
wr ipv4/tcp_app_win 0
wr ipv4/tcp_fack 1
wr ipv4/tcp_fin_timeout 30
wr ipv4/tcp_keepalive_intvl 30
wr ipv4/tcp_keepalive_probes 5
wr ipv4/tcp_keepalive_time 600
wr ipv4/tcp_max_syn_backlog 8192
wr ipv4/tcp_mtu_probing 1
wr ipv4/tcp_no_metrics_save 1
wr ipv4/tcp_low_latency 1
wr ipv4/tcp_rmem "65536 131072 16777216"
wr ipv4/tcp_rfc1337 1
wr ipv4/tcp_slow_start_after_idle 0
wr ipv4/tcp_synack_retries 3
wr ipv4/tcp_syn_retries 3
wr ipv4/tcp_tw_reuse 1
wr ipv4/tcp_wmem "65536 131072 16777216"
wr ipv4/udp_rmem_min 65536
wr ipv4/udp_wmem_min 65536

wr ipv6/conf/all/disable_ipv6 1

#############################################################
cd /proc/sys/vm
#############################################################

wr dirty_bytes 67108864
wr dirty_background_bytes 16777216
wr dirty_expire_centisecs 60000
wr dirty_writeback_centisecs 60000
wr min_free_kbytes 131072
wr oom_dump_tasks 0
wr oom_kill_allocating_task 1
wr overcommit_memory 1
wr overcommit_ratio 100
wr stat_interval 60
wr swappiness 10
wr vfs_cache_pressure 50
wr watermark_scale_factor 1000

#############################################################
cd /sys/kernel/mm/transparent_hugepage
#############################################################

wr defrag "never"
wr enabled "never"

#############################################################
cd /sys/block/sda/queue
#############################################################

wr add_random 0
wr iostats 0
wr max_sectors_kb $(cat max_hw_sectors_kb)
wr read_ahead_kb 1024
wr rq_affinity 2

wr scheduler "deadline"
wr iosched/fifo_batch 4
wr iosched/read_expire 500
wr iosched/write_expire 3000
wr iosched/writes_starved 3

#############################################################
exit 0
#############################################################
